version: "3"

services:
  lb:
    image: haproxy
    command: haproxy -f /etc/haproxy/haproxy.cfg
    ports:
      - "8080:80"
    volumes:
      - ./haproxy:/etc/haproxy

  app1:
    build: ./app
    container_name: app1
    environment:
      - APPID=app1
    volumes:
      - ./app:/app
  app2:
    build: ./app
    container_name: app2
    environment:
      - APPID=app2
    volumes:
      - ./app:/app
